export const endpoints = {
  agentsStats: '/agents/stats',
  checksStats: '/checks/stats',
  agents: '/agents',
  checks: '/checks',
  alerts: '/alerts',
  alertsStats: '/alerts/stats',
  singleCheck: id => `/checks/${id}`,
  checksSummaryDate: (id, date) => `/checks/${id}/summary/${date}`,
  checkLatency: id => `/checks/${id}/latency`,
  checkApdexHistory: id => `/checks/${id}/apdex`,
  checkHistory: id => `/checks/${id}/history`,
  checkHistoryDetail: (checkId, historyId) => `/checks/${checkId}/history/${historyId}`,
  checkHistogram: id => `/checks/${id}/histogram`,
  checkSummaryYearly: id => `/checks/${id}/summary/yearly`,
  singleAgent: id => `/agents/${id}`,
  agentMetric: id => `/agents/${id}/metrics`,
  agentHistory: id => `/agents/${id}/history`,
  agentHistoryDetail: (agentId, historyId) => `/agents/${agentId}/history/${historyId}`,
  agentCollectDuration: agentId => `/agents/${agentId}/collect-duration`,
  agentSummaryYearly: id => `/agents/${id}/summary/yearly`,
  agentSummaryDate: (id, date) => `/agents/${id}/summary/${date}`,
  agentChart: id => `/agents/${id}/chart`,
  singleAlert: id => `/alerts/${id}`,
  alertHistory: id => `/alerts/${id}/history`,
  alertHistoryDetail: (alertId, historyId) => `/alerts/${alertId}/history/${historyId}`,
  alertState: id => `/alerts/${id}/state`,

  //---------------

  login: '',
};
